
[functions.import-clients]
enabled = true
verify_jwt = false
import_map = "./functions/import-clients/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/import-clients/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/import-clients/*.html" ]

[functions.process-client-import]
enabled = true
verify_jwt = false
entrypoint = "./functions/process-client-import/index.ts"

[functions.ai-assistant]
enabled = true
verify_jwt = false
entrypoint = "./functions/ai-assistant/index.ts"

[functions.send-verification-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-verification-email/index.ts"

[functions.stripe-subscription]
enabled = true
verify_jwt = false
entrypoint = "./functions/stripe-subscription/index.ts"
