-- ─────────────────────────────────────────────────────────────────────────────
-- Affiliate Program — Phase 1: Schema, RLS, Commission Engine
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Commission tiers (monthly revenue generated by referred shops):
--   $0–$300  → 10%   $300–$800  → 20%   $800–$2,000 → 30%
--   $2,000–$5,000 → 40%   $5,000+ → 50%
-- Rate is flat (not marginal) — the tier the month's total falls into applies
-- to the ENTIRE month's revenue for that affiliate.
--
-- Revenue proxy: subscription tier MRR ($29 starter / $79 pro / $149 premium).
-- When Stripe billing is fully wired this query can be swapped for actual
-- invoice amounts with a one-line change in calculate_affiliate_commission().
-- Consider making the tier thresholds configurable in shop_settings if they
-- need to change frequently — they're currently hardcoded here.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1. affiliates ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.affiliates (
  id                 uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name               text        NOT NULL,
  email              text        NOT NULL,
  phone              text,
  social_media_links jsonb,                        -- {"instagram":"…","youtube":"…"}
  why_join           text,                         -- short "why do you want to join" field
  application_status text        NOT NULL DEFAULT 'pending'
                       CHECK (application_status IN
                             ('pending','approved','rejected','terminated')),
  applied_at         timestamptz NOT NULL DEFAULT now(),
  reviewed_at        timestamptz,
  reviewed_by        uuid        REFERENCES auth.users(id),
  promo_code         text        UNIQUE,           -- generated on approval, e.g. JOHNDOE10
  auth_user_id       uuid        UNIQUE REFERENCES auth.users(id),
  notes              text,                         -- internal admin notes
  created_at         timestamptz NOT NULL DEFAULT now()
);

-- ── 2. affiliate_referrals ────────────────────────────────────────────────────
-- One row per (affiliate, shop) pair; the shop signed up via the affiliate code.
CREATE TABLE IF NOT EXISTS public.affiliate_referrals (
  id                        uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  affiliate_id              uuid        NOT NULL REFERENCES public.affiliates(id),
  shop_id                   uuid        NOT NULL REFERENCES public.shops(id),
  signed_up_at              timestamptz NOT NULL DEFAULT now(),
  commission_window_ends_at timestamptz NOT NULL,  -- signed_up_at + 3 months
  created_at                timestamptz NOT NULL DEFAULT now(),
  UNIQUE(affiliate_id, shop_id)
);

-- ── 3. affiliate_commission_log ───────────────────────────────────────────────
-- Monthly commission snapshots. Populated by calculate_affiliate_commission()
-- (called on-the-fly for current month, or by monthly cron for past months).
-- On-the-fly is always accurate for the current month; cron snapshots are
-- cheaper for historical display since they avoid re-joining all subscriptions
-- every page load. Both paths use the same calculation function.
CREATE TABLE IF NOT EXISTS public.affiliate_commission_log (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  affiliate_id            uuid        NOT NULL REFERENCES public.affiliates(id),
  month                   date        NOT NULL,   -- first day of month, e.g. 2026-06-01
  total_revenue_generated numeric(10,2) NOT NULL DEFAULT 0,
  commission_rate_applied numeric(5,4) NOT NULL DEFAULT 0,  -- 0.10 = 10%
  commission_amount       numeric(10,2) NOT NULL DEFAULT 0,
  calculated_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE(affiliate_id, month)
);

-- ── 4. signup_attempts: track affiliate code at signup ───────────────────────
-- Stored here so the referral row can be created when the shop activates.
ALTER TABLE public.signup_attempts
  ADD COLUMN IF NOT EXISTS affiliate_code text;

-- ── 5. Commission calculation function ───────────────────────────────────────
-- Called on-the-fly for the current month, or by the monthly cron.
CREATE OR REPLACE FUNCTION public.calculate_affiliate_commission(
  p_affiliate_id uuid,
  p_month        date     -- pass any day in the target month; rounded to month-start
)
RETURNS TABLE (
  affiliate_id            uuid,
  month                   date,
  total_revenue_generated numeric,
  commission_rate_applied numeric,
  commission_amount       numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_month_start  date    := date_trunc('month', p_month)::date;
  v_month_end    date    := (date_trunc('month', p_month) + interval '1 month')::date;
  v_revenue      numeric := 0;
  v_rate         numeric;
BEGIN
  -- Sum monthly subscription revenue for all referred shops whose commission
  -- window overlaps the target month and whose subscription is/was active.
  SELECT COALESCE(SUM(
    CASE
      WHEN s.tier = 'starter'  THEN 29
      WHEN s.tier = 'pro'      THEN 79
      WHEN s.tier = 'premium'  THEN 149
      ELSE 0
    END
  ), 0)
  INTO v_revenue
  FROM public.affiliate_referrals ar
  JOIN public.subscriptions s ON s.shop_id = ar.shop_id
  WHERE ar.affiliate_id = p_affiliate_id
    AND ar.signed_up_at              < v_month_end    -- referral started before month ends
    AND ar.commission_window_ends_at > v_month_start  -- window hadn't ended by month start
    AND s.status IN ('active', 'trialing');

  -- Flat-rate sliding scale (not marginal — tier applies to entire month's revenue)
  v_rate := CASE
    WHEN v_revenue < 300   THEN 0.10
    WHEN v_revenue < 800   THEN 0.20
    WHEN v_revenue < 2000  THEN 0.30
    WHEN v_revenue < 5000  THEN 0.40
    ELSE                        0.50
  END;

  RETURN QUERY SELECT
    p_affiliate_id,
    v_month_start,
    v_revenue,
    v_rate,
    round(v_revenue * v_rate, 2);
END;
$$;

-- Internal only — not callable by anon or normal shop users.
REVOKE EXECUTE ON FUNCTION public.calculate_affiliate_commission(uuid, date)
  FROM anon, authenticated;

-- ── 6. Snapshot helper ────────────────────────────────────────────────────────
-- Upserts one commission_log row for a given affiliate + month.
CREATE OR REPLACE FUNCTION public.snapshot_affiliate_commission(
  p_affiliate_id uuid,
  p_month        date
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rec record;
BEGIN
  SELECT * INTO rec
  FROM public.calculate_affiliate_commission(p_affiliate_id, p_month);

  INSERT INTO public.affiliate_commission_log
    (affiliate_id, month, total_revenue_generated,
     commission_rate_applied, commission_amount, calculated_at)
  VALUES
    (rec.affiliate_id, rec.month, rec.total_revenue_generated,
     rec.commission_rate_applied, rec.commission_amount, now())
  ON CONFLICT (affiliate_id, month) DO UPDATE SET
    total_revenue_generated = EXCLUDED.total_revenue_generated,
    commission_rate_applied = EXCLUDED.commission_rate_applied,
    commission_amount       = EXCLUDED.commission_amount,
    calculated_at           = now();
END;
$$;

REVOKE EXECUTE ON FUNCTION public.snapshot_affiliate_commission(uuid, date)
  FROM anon, authenticated;

-- ── 7. Monthly cron: snapshot all affiliates on the 2nd of each month ────────
-- Runs after billing cycles settle. Snapshots the previous calendar month.
CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE OR REPLACE FUNCTION public.run_monthly_affiliate_commission_snapshots()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  aff        record;
  prev_month date := date_trunc('month', now() - interval '1 month')::date;
BEGIN
  FOR aff IN
    SELECT id FROM public.affiliates
    WHERE application_status = 'approved'
  LOOP
    PERFORM public.snapshot_affiliate_commission(aff.id, prev_month);
  END LOOP;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.run_monthly_affiliate_commission_snapshots()
  FROM anon, authenticated;

SELECT cron.schedule(
  'affiliate-commission-monthly',
  '0 10 2 * *',   -- 10:00 UTC on the 2nd of each month
  $$ SELECT public.run_monthly_affiliate_commission_snapshots(); $$
);


-- ── 8. RLS ─────────────────────────────────────────────────────────────────────
ALTER TABLE public.affiliates            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_referrals   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_commission_log ENABLE ROW LEVEL SECURITY;

-- affiliates: superadmin/owner full access
CREATE POLICY "affiliates_admin_all" ON public.affiliates
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.barbers
      WHERE user_id = auth.uid()
        AND permission_level = ANY(ARRAY['owner','manager','superadmin'])
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.barbers
      WHERE user_id = auth.uid()
        AND permission_level = ANY(ARRAY['owner','manager','superadmin'])
    )
  );

-- affiliates: an affiliate reads only their own row
CREATE POLICY "affiliates_self_read" ON public.affiliates
  FOR SELECT TO authenticated
  USING (auth_user_id = auth.uid());

-- affiliates: anon can INSERT to submit an application
-- Constraints prevent setting privileged fields at apply time.
CREATE POLICY "affiliates_anon_apply" ON public.affiliates
  FOR INSERT TO anon
  WITH CHECK (
    application_status = 'pending'
    AND auth_user_id IS NULL
    AND promo_code    IS NULL
    AND reviewed_at   IS NULL
    AND reviewed_by   IS NULL
  );

-- affiliate_referrals: admin full access
CREATE POLICY "affiliate_referrals_admin_all" ON public.affiliate_referrals
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.barbers
      WHERE user_id = auth.uid()
        AND permission_level = ANY(ARRAY['owner','manager','superadmin'])
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.barbers
      WHERE user_id = auth.uid()
        AND permission_level = ANY(ARRAY['owner','manager','superadmin'])
    )
  );

-- affiliate_referrals: affiliate reads own rows only
CREATE POLICY "affiliate_referrals_self_read" ON public.affiliate_referrals
  FOR SELECT TO authenticated
  USING (
    affiliate_id IN (
      SELECT id FROM public.affiliates
      WHERE auth_user_id = auth.uid()
        AND application_status = 'approved'
    )
  );

-- affiliate_commission_log: admin full access
CREATE POLICY "affiliate_commission_admin_all" ON public.affiliate_commission_log
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.barbers
      WHERE user_id = auth.uid()
        AND permission_level = ANY(ARRAY['owner','manager','superadmin'])
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.barbers
      WHERE user_id = auth.uid()
        AND permission_level = ANY(ARRAY['owner','manager','superadmin'])
    )
  );

-- affiliate_commission_log: affiliate reads own rows only
CREATE POLICY "affiliate_commission_self_read" ON public.affiliate_commission_log
  FOR SELECT TO authenticated
  USING (
    affiliate_id IN (
      SELECT id FROM public.affiliates
      WHERE auth_user_id = auth.uid()
        AND application_status = 'approved'
    )
  );
